# Generated by Django 3.1.5 on 2021-01-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('mbti', models.TextField()),
                ('artist', models.TextField()),
                ('songs', models.TextField()),
                ('grade', models.TextField()),
            ],
        ),
    ]
